#!/usr/bin/env ruby
require 'net/http'
require 'json'

message_file = ARGV[0]
message      = File.read(message_file)
$regex       = /#(\d+)/

if $regex.match message
  number = message[/#(\d+)/]
  number = number[/(\d+)/]
  @return =  JSON.parse(Net::HTTP.get(URI("https://api.github.com/repos/adelinosegundo/gcm-bank/issues")))
  @return.each do |issue|

    labels = []
    issue['labels'].each do |label|
      labels << label["name"]
    end

    exit 0 if number == issue['number'].to_s && labels.include?("implementing")
  end
  puts "Issue implentations has not been started"
  exit 1
else
  puts "No issue referenced"
  exit 1
end
