# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 495cbc68b69dce67b522c889bed8dccf565ccdd2525c1e02165d9a70af3455a8cd5897fefba368cdf96cc306445735c04859ada8eaaf23b10a81a514bfb4cdff

test:
  secret_key_base: 81e0c6637cbe5e8c6537c8c7df87cdb27e745f75992d3a434261f132bb4f896679e8a6d423564db557589e998c3e71717ed36ede86f4317353c25898096bd41b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
